### PR TITLE
Ruby SDK

### PR DESCRIPTION
**Pull request by tungnt1203**
Ruby SDK for the Minds API, providing similar functionality to the existing Python SDK:

This repo:  https://github.com/tungnt1203/minds_ruby_sdk
>Issue https://github.com/mindsdb/minds_python_sdk/issues/22

- Client class for API authentication and requests
- Classes for managing Datasources and Minds
- CRUD operations for resources
- Mind completion support
- Error handling

### CODE REVIEW

**Comment by tungnt1203** [comment]
@quest-bot loot #22

**Comment by tungnt1203** [comment]
I have read the CLA Document and I hereby sign the CLA

**Comment by tungnt1203** [comment]
@ea-rus  can you please review this PR?

**Comment by tungnt1203** [comment]
@ZoranPandovski updated

**Review by ZoranPandovski — APPROVED** [review]
Thanks

**Pull request merged**
