### PR TITLE
Adds C# SDK in Readme

### LINKED ISSUE #25: Minds C# SDK
Short description of current behavior
The goal of this issue is to develop a new C# SDK for Minds.

Steps 🕵️‍♂️ 🕵️‍♀️
You can familiarize yourself with [Minds](https://mindsdb.com/).
Review the existing [Python SDK](https://github.com/mindsdb/minds_python_sdk) as a reference.
Create a new repository in your account and submit a Pull Request (PR) to this repository, adding the new SDK to the Other SDKs section of the README.
Multiple contributors are welcome, but the SDK with the highest standards—such as clear documentation, robust tests, and overall code quality—will be accepted.
📢 Additional rewards 🏆
This issue brings 1️⃣ 2️⃣ 0️⃣ points for SWAG and entry into the draw for a 👇 :

3️⃣ ❌ 💻 [Razer Blade 16 Gaming Laptop](https://www.razer.com/gaming-laptops/Razer-Blade-16/RZ09-0510TEN3-R3U1)
👕 🐻 [MindsDB Swag](https://store.covver.io/mindsdb/collections/swag-collection)
ℹ️ For more info check out https://mindsdb.com/hacktoberfest 👈

### PR DESCRIPTION
**Pull request by priyanshuverma-dev**
SDK Repository: https://github.com/priyanshuverma-dev/Minds.SDK
By [Priyanshu Verma](https://github.com/priyanshuverma-dev)

- closes #25

### CODE REVIEW

**Comment by priyanshuverma-dev** [comment]
@quest-bot loot #25

**Comment by priyanshuverma-dev** [comment]
I have read the CLA Document and I hereby sign the CLA

**Comment by priyanshuverma-dev** [comment]
recheck

**Comment by priyanshuverma-dev** [comment]
@ea-rus Please Review this PR.

**Review by ZoranPandovski — APPROVED** [review]

**Pull request merged**
