### PR TITLE
🎯 Showcase Dart Minds SDK

### LINKED ISSUE #20: Minds Dart SDK
## Short description of current behavior

The goal of this issue is to develop a new Dart SDK for Minds.

## Steps 🕵️‍♂️ 🕵️‍♀️

- You can familiarize yourself with [Minds](https://mindsdb.com/).
- Review the existing [Python SDK](https://github.com/mindsdb/minds_python_sdk) as a reference.
- Create a new repository in your account and submit a Pull Request (PR) to this repository, adding the new SDK to the Other SDKs section of the README.
- Multiple contributors are welcome, but the SDK with the highest standards—such as clear documentation, robust tests, and overall code quality—will be accepted.

## 📢 Additional rewards 🏆
This issue brings 1️⃣ 2️⃣ 0️⃣ points for SWAG and entry into the draw for a 👇 :

-  3️⃣ ❌ 💻 [Razer Blade 16 Gaming Laptop](https://www.razer.com/gaming-laptops/Razer-Blade-16/RZ09-0510TEN3-R3U1)
👕 🐻 [MindsDB Swag](https://store.covver.io/mindsdb/collections/swag-collection)
- ℹ️ For more info check out https://mindsdb.com/hacktoberfest 👈

### PR DESCRIPTION
**Pull request by ArnavK-09**
🎯 https://github.com/ArnavK-09/mdb_dart

> resolves #20

### CODE REVIEW

**Comment by ArnavK-09** [comment]
@quest-bot loot #20

**Comment by ArnavK-09** [comment]
I have read the CLA Document and I hereby sign the CLA

**Comment by ArnavK-09** [comment]
recheck

**Review by ZoranPandovski — APPROVED** [review]
Thank you

**Pull request merged**
